server:
  port: 8080
spring:
  #配置mysql

  datasource:
    username: root
    password: root
    #mysql8版本以上的驱动包，需要指定以下时区
    url: jdbc:mysql://127.0.0.1:3307/bill?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #引入Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  #配置 redis缓存
  redis:
    host: 127.0.0.1
    port: 6379

#配置mybatis相关文件路径
mybatis:
  #映射配置文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  #核心配置文件路径
  config-location: classpath:mybatis/mybatis-config.xml
  #开启驼峰命名方式
  #configuration:
    #map-underscore-to-camel-case: true

#配置日志级别
logging:
  level:
    springcaching:
      modules:
        dao: debug